[package]
name = "problem6"
version = "0.1.0"
authors = ["Matt Versweyveld <mversweyveld@cars.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
strum = "0.15"
strum_macros = "0.15"
rand_core = "0.6.3"